config:
  info: 123啊大大 2
spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:orcl
    driver-class-name: oracle.jdbc.driver.OracleDriver
    username: C##SHANE
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource

  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        prefer-ip-address: true
