spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:orcl
    driver-class-name: oracle.jdbc.driver.OracleDriver
    username: C##SHANE
    password: 1234561
    type: com.alibaba.druid.pool.DruidDataSource

  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        prefer-ip-address: true

  rabbitmq:
    password: shane
    username: shane
    host: localhost
    port: 5672