spring:
  datasource:
    url: jdbc:p6spy:oracle:thin:@localhost:1521:orcl
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    username: c##shane
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource