spring:
  datasource:
    url: jdbc:p6spy:oracle:thin:@localhost:1521:xe
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    username: shane
    password: shane
    type: com.alibaba.druid.pool.DruidDataSource