spring:
  cloud:
    consul:
      port: 8500
      host: localhost
      discovery:
        prefer-ip-address: true
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
          prefer-ip-address: true

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: 'http://localhost:6001/rsa/publicKey'  # 配置RSA的公钥访问地址
  redis:
    host: localhost
    port: 6379
  main:
    allow-bean-definition-overriding: true

secure:
  ignore:
    urls: # 配置白名单路径
      - "/actuator/**"
      - "/oauth2-server/oauth/token"
