spring:
  cloud:
    consul:
      port: 8500
      host: localhost
      discovery:
        prefer-ip-address: true

    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
  main:
    allow-bean-definition-overriding: true

  redis:
    host: localhost
    port: 6379


